### ISSUE TITLE
[feat request]: plz add contentious animation!

### ISSUE THREAD

**Issue by thgreasi** [TheT0dd/tesserae#1]
I will be like subtle patterns but with animating smoothly constantly!

**Comment by cvara** [comment]
There is the [**live**](https://github.com/TheT0dd/tesserae#live) setting introduced in 0.10.0 that seems to do what you describe but I had forgotten to update the demo. You can take a look at the [**updated demo**](https://thet0dd.github.io/tesserae/) and tell me if this is what you had in mind.

**Comment by thgreasi** [comment]
@TheT0dd Yea that's it!
I will just have to find the ideal options to make it live enough (something like 1-5), since with the (large enough) initial values, I couldn't tell the difference in the demo page.

**Comment by cvara** [comment]
You are right, the animation is not prominent enough, and tampering with the intervals alone does not cut it. Aim to fix this, view #2
